### ISSUE TITLE
Does not compile with latest zig (0.11.0-dev.3971+6bc9c4f71)

### ISSUE THREAD

**Issue by gensss** [cryptocode/zigfsm#2]
Few things changed in zig.

I have fixed it up locally, as well as i could understand. Tests pass.
Should i send a pull request ? I'm not knowledgeable about these collaborative things.

**Comment by cryptocode** [comment]
Yes, feel free to send a PR. I generally update my projects to latest master every few months, but nothing beats getting a PR ;)

**Comment by cryptocode** [comment]
Appreciate the report!

The latest commit upgrades to Zig version `0.11.0-dev.4003+c6aa29b6f`

Feel free to submit a PR in the future when you notice breakage.

**Comment by gensss** [comment]
Will do.

On line 87 i thought it is a compiler/stdlib bug, so i added 1 to both values as a workaround.
`const CellType = std.meta.Int(.unsigned, @max(state_enum_bits + 1, event_enum_bits + 1));`
Seems weird to me, should i report it to them ?

By the way; interesting project, thanks for it.

**Comment by cryptocode** [comment]
The old `std.math.max` used peer resolution of the arguments to determine the return type, while `@max` makes a type exactly large enough to hold the result (if comptime known)

I haven't checked the rationale for this change, but that's the reason I cast to the expected type of `std.meta.Int` before adding 1. That seems semantically most correct to me, given how the `@max` intrinsic works.

(I've submitted a question on the Zig discord about this)
